import pickle
import os

def simulate_victim():
    print("Simulating Victim Substrate (Loading pytorch_model.bin)...")
    
    # Path to the PoC artifact generated by Garu
    model_path = os.path.join(os.path.dirname(__file__), "pytorch_model.bin")
    marker_path = "garu_0x52_displacement_verified.txt"
    
    print(f" -> Attempting to unpickle {model_path}...")
    
    try:
        # THE VULNERABILITY:
        with open(model_path, "rb") as f:
            pickle.load(f)
            
        print(" -> Model loaded. Checking for payload execution...")
        
        # Verify if the payload executed
        if os.path.exists(marker_path):
            print("\n[CRITICAL] VULNERABILITY VERIFIED: ARBITRARY CODE EXECUTION DETECTED.")
            print(f" -> The marker file '{marker_path}' was successfully created by the malicious object.")
        else:
            print("\n[FAILED] The payload did not execute as expected.")
            
    except Exception as e:
        print(f"\n[ERROR during simulation]: {e}")

if __name__ == "__main__":
    simulate_victim()
